"""
Core data models for the Staffing Agency RL environment.
All dataclasses are mutable plain Python objects (no Pydantic overhead in hot loop).
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Candidate
# ---------------------------------------------------------------------------

@dataclass
class Candidate:
    id: str
    developer_type: str           # backend | frontend | fullstack | ml_engineer | devops
    seniority_level: str          # junior | mid | senior
    skill_score: float            # 0.0 – 1.0

    base_rating: int = 0          # 1–5, set after interview
    project_fit_rating: int = 0   # 1–5, set after match
    composite_rating: float = 0.0 # 0.4×base + 0.6×fit

    salary_weekly: float = 0.0
    client_rate_weekly: float = 0.0
    margin_weekly: float = 0.0
    salary_expectation: float = 0.0   # minimum acceptable weekly salary
    ttl_weeks: int = 8                 # market TTL (set at generation, organic churn countdown)

    patience_remaining: int = 8
    status: str = "available"         # available|in_pipeline|pending_hire|hired|placed
    assigned_project: Optional[str] = None
    assigned_role: Optional[str] = None

    weeks_on_bench: int = 0
    contract_weeks_left: Optional[int] = None

    # interview result details (for info/logging)
    technical_score: float = 0.0
    communication: float = 0.0
    culture_fit: float = 0.0
    red_flags: list = field(default_factory=list)
    interview_summary: str = ""

    def to_dict(self) -> dict:
        return self.__dict__.copy()


# ---------------------------------------------------------------------------
# Role & Project
# ---------------------------------------------------------------------------

@dataclass
class Role:
    role_id: str
    developer_type: str
    seniority: str
    min_skill_score: float
    headcount: int
    bill_rate_weekly: float = 0.0
    filled_count: int = 0
    assigned: list = field(default_factory=list)   # list of candidate_ids

    @property
    def is_filled(self) -> bool:
        return self.filled_count >= self.headcount

    def to_dict(self) -> dict:
        d = self.__dict__.copy()
        d["is_filled"] = self.is_filled   # include @property for clients
        return d


@dataclass
class Project:
    project_id: str
    client_id: str
    roles: list = field(default_factory=list)   # list[Role]
    deadline_remaining: int = 6
    fill_status: str = "OPEN"          # OPEN | PARTIAL | SEALED
    match_score: float = 0.0           # avg match quality across filled roles
    confirmed: bool = False
    weekly_revenue: float = 0.0        # $0 until SEALED

    def update_fill_status(self) -> None:
        if not self.roles:
            return
        total_needed = sum(r.headcount for r in self.roles)
        total_filled = sum(r.filled_count for r in self.roles)
        if total_filled == 0:
            self.fill_status = "OPEN"
        elif total_filled < total_needed:
            self.fill_status = "PARTIAL"
        else:
            self.fill_status = "SEALED"

    def to_dict(self) -> dict:
        d = self.__dict__.copy()
        d["roles"] = [r.to_dict() for r in self.roles]
        return d


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------

@dataclass
class Client:
    client_id: str
    industry: str
    satisfaction_score: float = 0.75
    churn_risk: bool = False
    num_projects_submitted: int = 0
    num_projects_filled: int = 0
    num_projects_expired: int = 0
    total_billed: float = 0.0
    total_paid: float = 0.0
    projects: list = field(default_factory=list)   # list[Project]
    event_history: list = field(default_factory=list)

    @property
    def num_open_projects(self) -> int:
        return sum(1 for p in self.projects if p.fill_status != "SEALED")

    @property
    def contracted_rate(self) -> float:
        return 100_000 / 52   # $1,923/wk

    def to_dict(self) -> dict:
        d = {k: v for k, v in self.__dict__.items() if k != "projects"}
        d["num_open_projects"] = self.num_open_projects
        d["projects"] = [p.to_dict() for p in self.projects]
        return d


# ---------------------------------------------------------------------------
# AgencyState  (snapshot, not live — generated by get_agency_state())
# ---------------------------------------------------------------------------

@dataclass
class AgencyState:
    cash_balance: float
    current_revenue: float
    current_costs: float
    current_profit: float
    num_candidates_hired: int
    num_candidates_placed: int
    num_candidates_benched: int
    num_candidates_in_interview: int
    placement_rate: float
    avg_time_to_place: float
    pending_payments: list
    burn_rate: float
    cash_runway_weeks: float

    def to_dict(self) -> dict:
        return self.__dict__.copy()
